---
title: "Top 3 pacotes pra usar com rmarkdown"
date: "2017-07-15T23:26:00+03:00"
tags: ["r-markdown", "rstudio"]
categories: ["top-10", "r"]
banner: "img/banners/tufte.jpg"
author: ["Fernando"]
summary: "Neste post, vou listar três pacotes que são úteis pra fazer relatórios bonitos em Rmarkdown."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```


Os criadores do Markdown, segundo suas próprias palavras, criaram a linguagem com o objetivo de construir um "formato de texto fácil de ler, fácil de escrever e opcionalmente conversível para HTML"[^criacao_rmd]. Com o passar do tempo, esse objetivo foi expandido pela comunidade, pois a simplicidade também é útil para outros formatos.

As extensões andam em dois sentidos. Um deles é construir tradutores universais entre todas as linguagens de marcação, como o `pandoc`, permitindo que seja fácil construir documentos a partir de textos em Markdown. A outra classe de extensões incorpora as vantagens obtidas a outras ferramentas, como o `Rmarkdown`, que adiciona o resultado de códigos em R aos textos escritos em Markdown. 

Essa segunda classe de extensões é particularmente importante para os estatísticos, já que a comunicação é uma parte muito importante do seu trabalho. Usando `Rmarkdown`, é fácil construir relatórios reprodutíveis, concisos e, por último mas não menos importante, bonitos. 

Neste post, vou listar pra vocês os meus 3 pacotes favoritos para formatar e organizar documentos em Rmarkdown, descrevendo brevemente o que eu mais gosto neles. Os três pacotes, assim como o próprio pacote `rmarkdown`, estão sendo desenvolvidos pela comunidade e pelo Rstudio, de tal forma que não vou mencionar explicitamente nenhuma das pessoas envolvidas nos projetos, mas antes de começar a lista quero deixar registrado que muito do que a gente tem hoje foi culpa do Yihui Xie. Muito obrigado, Yihui! 

# Primeira posição: `rticles`

O pacote `rticles` contém vários templates para documentos em `rmarkdown`. Os modelos são todos baseados nos padrões de artigos acadêmicos, mas eles são bonitos e flexíveis o suficiente para garantir sua aplicabilidade em vários outros contextos.

Pra aplicações mais gerais, acho o template da _Statistic in Medicine_ bastante adequado.

# Segunda posição: `tufte`

Na nossa segunda posição, vem o pacote `tufte`. Ele contém templates para documentos em `rmarkdown` e ferramentas gráficas que se baseiam nas práticas de visualização do Edward Tufte [^tufte], sujeito que está no banner desse post. A ideia aqui é construir relatórios fluidos e que incorporem formas de informação quantitativas (gráficos e tabelas) de maneira mais fluida.

Vendo alguns exemplos no [site do Rstudio](http://rmarkdown.rstudio.com/tufte_handout_format.html) dá pra ver como a coisa é elegante e prática. A grande sacada é usar a margem com mais liberdade: algumas notas de rodapé, por exemplo, na verdade são pequenos comentários, então você pode inseri-los na margem da página pra sugerir essa relação mais íntima com o que você escreveu. 

[^tufte]: https://www.edwardtufte.com/tufte/

# Terceira posição: `bookdown`

Na terceira posição vem um pacote um pouco mais jovem do que os anteriores. Dessa vez o objetivo é construir documentos mais longos, como uma apostila ou um relatório. A estrutura de arquivos é bastante simples e é possível criar capítulos, seções, sumários etc como se você estivesse rascunhando alguma coisa em `rmarkdown`. 

Além de estruturar a escrita de um documento grande, esse pacote também se comunica bem com o `tufte` e já prevê alguma maneiras de publicar o seu trabalho. É possível compilar os _books_ em um html, mais ou menos como os livros do [Hadley](http://rmarkdown.rstudio.com/tufte_handout_format.html), ou num pdf, sugerindo uma maneira bem legal de escrever uma dissertação ou uma tese. Se você integrar o _bookdown_ com [Travis](https://travis-ci.org/), então, o céu é o limite.

[^criacao_rmd]: https://web.archive.org/web/20040402182332/http://daringfireball.net/projects/markdown/