---
title: "Estatística e programação"
date: "2017-12-09T11:54:00+03:00"
tags: ["estatística"]
categories: ["discussões", "r"]
banner: "img/banners/dog-pc.jpg"
author: ["William"]
summary: "Neste post, encerraremos a nossa série sobre aprendizado e educação discutindo a importância da programação dentro da Estatística."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Não importa a área de atuação, a maior parte do dia do estatístico é atrás do computador. E desse tempo, a maior parte é atrás de um (geralmente único) programa estatístico. 

Os principais programas hoje em dia permitem a execução das etapas essenciais de uma análise: interação com banco de dados, transformação, criação de visualizações e modelagem. Alguns vão além e auxiliam na comunicação dos resultados. Também é comum a existência de ambientes de programação, mesmo quando o programa é bem estruturado no *point and click*.

Eu considero a programação primordial para um estatístico. Ela nos dá a liberdade para sermos criativos, para não nos limitarmos em técnicas que alguém criou e todo mundo usa. Para mim, um estatístico que não sabe/gosta de programar é igual a um piloto que só dirige carro automático.

É por isso que o R é uma ferramenta tão incrível para se trabalhar. Ele pega a sua mão no momento em que você recebe a base de dados, estando ela arrumada ou não, e só solta depois da sua análise estar devidamente divulgada. Para cada problema, o R te fornece todas as peças e te deixa montar do jeito que quiser. E mesmo quando uma peça não existe, você mesmo pode criá-la ou pedir socorro para a comunidade mais que fantástica de erreiros pelo mundo. 

Claro que aprender a programar\footnote{Não só em R ou outra linguagem específica, mas aprender a lógica de programação.} é bem custoso. Para quem nunca foi familiar com a computação, vai ser um caminho bem tortuoso no início. Mas como discutimos no último post, não existe aprendizado de graça, e por mais que você não goste de estudar programação, é um investimento com retorno mais do que garantido.

Assim, encerro essa série de discussões. Fazendo um resumão do que falamos até aqui, podemos enumerar os seguintes itens:

- A Estatística é uma disciplina fantástica, principalmente para quem gosta de aprender, e o mercado está bombando.

- Aprender Estatística é difícil, assim como todo conhecimento. O que vai limitar a sua capacidade de aprender é o quanto você vai conseguir dominar a sua preguiça de estudar.

- A Estatística e a programação andam lado a lado. O Estatístico que sabe programar tem muito mais poder para resolver problemas complicados.

- O R é o ambiente mais legal para trabalhar com Estatística. :D

É isso! Espero que possamos continuar discutindo o quanto é legal trabalhar com Estatística e que cada vez mais pessoas se interessem por esse caminho difícil, mas recompensador.


